#!/usr/bin/env ruby

if Dir.exist?('spec') && `git diff --cached spec` =~ /,\s?(:focus|focus:\s?true|:focus\s?=>\s?true)/
  puts "\e[31mPlease focus and remove your :focus tags before committing :)"
  exit 1
end
