AccessModifierIndentation:
  EnforcedStyle: outdent
ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 2000
MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
